version: '3'
services:
  node-server:
    build: .
    ports:
      - "5000:5000"
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - datadog-agent

    environment:
      - DD_SERVICE=node-server
      - DD_VERSION=0.0.0.1
      - DD_ENV="test"
      - DD_LOGS_INJECTION=true
#      - DD_PROFILING_ENABLED=true
      - DD_APPSEC_ENABLED=true
# Single Step instrumentation
#      - DD_INSTRUMENT_SERVICE_WITH_APM=true
      - DD_TRACE_DEBUG=false 
      - DD_AGENT_HOST=datadog-agent
      - DD_DYNAMIC_INSTRUMENTATION_ENABLED=true

  datadog-agent:
    image: datadog/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro \
      - /proc/:/host/proc/:ro

    ports:
      - "8126:8126/tcp"
      
    environment:
      - DD_SITE=datadoghq.com
      - DD_API_KEY=${DD_API_KEY}
      - DD_APM_NON_LOCAL_TRAFFIC=true      
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true

      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true


    
